# Zarr Store Inspector

Point this notebook at any local or GCS Zarr store to get a complete picture of its contents before writing any retrieval code.

In [1]:
from pathlib import Path
import sys

import gcsfs
import numpy as np
import xarray as xr
import pandas as pd

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
SRC_PATH = PROJECT_ROOT / "src"
if str(SRC_PATH) not in sys.path:
    sys.path.insert(0, str(SRC_PATH))

print("Project root:", PROJECT_ROOT)

Project root: /Users/chxmr/code/glide

## Configure Store Path

Set `STORE_PATH` to a local directory or a `gs://` URI.  
Set `USE_ANONYMOUS` to `False` if the bucket requires credentials.

In [2]:
STORE_PATH = "gs://gcp-public-data-arco-era5/ar/full_37-1h-0p25deg-chunk-1.zarr-v3"
USE_ANONYMOUS = True   # set False to use application-default credentials

def open_store(path: str, anonymous: bool = True) -> xr.Dataset:
    if path.startswith("gs://"):
        token = "anon" if anonymous else "google_default"
        fs = gcsfs.GCSFileSystem(token=token)
        mapper = fs.get_mapper(path)
        return xr.open_zarr(mapper, consolidated=True, chunks={})
    return xr.open_zarr(path, consolidated=True, chunks={})

ds = open_store(STORE_PATH, anonymous=USE_ANONYMOUS)
print("Store opened:", STORE_PATH)

I0402 10:25:03.884965 8804859 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers
I0402 10:25:03.888767 8804880 ev_poll_posix.cc:593] FD from fork parent still in poll list: fd(100, generation: 1)

Store opened: gs://gcp-public-data-arco-era5/ar/full_37-1h-0p25deg-chunk-1.zarr-v3

## Dimensions

In [3]:
dim_rows = [{"dimension": k, "size": v} for k, v in ds.sizes.items()]
pd.DataFrame(dim_rows).set_index("dimension")

              size
dimension
time       1323648
latitude       721
longitude     1440
level           37

## Coordinates

Shape, dtype, units/calendar where present, and first/last values.

In [4]:
coord_rows = []
for name, coord in ds.coords.items():
    attrs = coord.attrs
    vals = coord.values
    first = vals.flat[0] if vals.size > 0 else None
    last  = vals.flat[-1] if vals.size > 0 else None
    coord_rows.append({
        "coordinate": name,
        "dims": str(coord.dims),
        "shape": str(coord.shape),
        "dtype": str(coord.dtype),
        "units / calendar": attrs.get("units", attrs.get("calendar", "")),
        "first": first,
        "last": last,
    })
pd.DataFrame(coord_rows).set_index("coordinate")

,dims,shape,dtype,units / calendar,first,last
coordinate,,,,,,
latitude,"('latitude',)","(721,)",float32,degrees_north,90.0,-90.0
level,"('level',)","(37,)",int64,Hectopascal(hPa),1,1000
longitude,"('longitude',)","(1440,)",float32,degrees_east,0.0,359.75
time,"('time',)","(1323648,)",datetime64[ns],,1900-01-01T00:00:00.000000000,2050-12-31T23:00:00.000000000

## Data Variables

Shape, dtype, units, long_name, and estimated uncompressed size per variable.

In [5]:
var_rows = []
for name, da in ds.data_vars.items():
    attrs = da.attrs
    nbytes = int(np.prod(da.shape)) * np.dtype(da.dtype).itemsize
    var_rows.append({
        "variable": name,
        "dims": str(da.dims),
        "shape": str(da.shape),
        "dtype": str(da.dtype),
        "units": attrs.get("units", ""),
        "long_name": attrs.get("long_name", ""),
        "uncompressed MiB": round(nbytes / 1024**2, 1),
    })
pd.DataFrame(var_rows).set_index("variable")

,dims,shape,dtype,units,long_name,uncompressed MiB
variable,,,,,,
100m_u_component_of_wind,"('time', 'latitude', 'longitude')","(1323648, 721, 1440)",float32,m s**-1,100 metre U wind component,5242402.3
100m_v_component_of_wind,"('time', 'latitude', 'longitude')","(1323648, 721, 1440)",float32,m s**-1,100 metre V wind component,5242402.3
10m_u_component_of_neutral_wind,"('time', 'latitude', 'longitude')","(1323648, 721, 1440)",float32,m s**-1,Neutral wind at 10 m u-component,5242402.3
10m_u_component_of_wind,"('time', 'latitude', 'longitude')","(1323648, 721, 1440)",float32,m s**-1,10 metre U wind component,5242402.3
10m_v_component_of_neutral_wind,"('time', 'latitude', 'longitude')","(1323648, 721, 1440)",float32,m s**-1,Neutral wind at 10 m v-component,5242402.3
...,...,...,...,...,...,...
wave_spectral_directional_width_for_wind_waves,"('time', 'latitude', 'longitude')","(1323648, 721, 1440)",float32,radians,Wave spectral directional width for wind waves,5242402.3
wave_spectral_kurtosis,"('time', 'latitude', 'longitude')","(1323648, 721, 1440)",float32,dimensionless,Wave spectral kurtosis,5242402.3
wave_spectral_peakedness,"('time', 'latitude', 'longitude')","(1323648, 721, 1440)",float32,dimensionless,Wave spectral peakedness,5242402.3
wave_spectral_skewness,"('time', 'latitude', 'longitude')","(1323648, 721, 1440)",float32,dimensionless,Wave Spectral Skewness,5242402.3
zero_degree_level,"('time', 'latitude', 'longitude')","(1323648, 721, 1440)",float32,m,0 degrees C isothermal level (atm),5242402.3

## Chunk Layout

Understanding chunks is critical for efficient bounding-box retrieval — ideally your spatial slice aligns with chunk boundaries.

In [6]:
chunk_rows = []
for name in ds.data_vars:
    encoding = ds[name].encoding
    chunk_rows.append({
        "variable": name,
        "chunks": encoding.get("chunks", "not set"),
        "compressor": str(encoding.get("compressor", "none")),
        "dtype (stored)": encoding.get("dtype", ds[name].dtype),
    })
pd.DataFrame(chunk_rows).set_index("variable")

,chunks,compressor,dtype (stored)
variable,,,
100m_u_component_of_wind,"(1, 721, 1440)",none,float32
100m_v_component_of_wind,"(1, 721, 1440)",none,float32
10m_u_component_of_neutral_wind,"(1, 721, 1440)",none,float32
10m_u_component_of_wind,"(1, 721, 1440)",none,float32
10m_v_component_of_neutral_wind,"(1, 721, 1440)",none,float32
...,...,...,...
wave_spectral_directional_width_for_wind_waves,"(1, 721, 1440)",none,float32
wave_spectral_kurtosis,"(1, 721, 1440)",none,float32
wave_spectral_peakedness,"(1, 721, 1440)",none,float32
wave_spectral_skewness,"(1, 721, 1440)",none,float32
zero_degree_level,"(1, 721, 1440)",none,float32

## Dataset-level Attributes

In [7]:
if ds.attrs:
    for k, v in ds.attrs.items():
        print(f"{k}: {v}")
else:
    print("No dataset-level attributes.")

last_updated: 2026-04-02 02:31:50.473162+00:00
valid_time_start: 1940-01-01
valid_time_stop: 2025-12-31
valid_time_stop_era5t: 2026-03-27

## Time Coverage

In [8]:
time_candidates = [c for c in ds.coords if "time" in c.lower()]
for tc in time_candidates:
    t = ds[tc]
    vals = t.values
    n = t.size
    step = (vals[1] - vals[0]) if n > 1 else "N/A"
    print(f"{tc}: {vals[0]}  →  {vals[-1]}  ({n} steps, step={step})")

time: 1900-01-01T00:00:00.000000000  →  2050-12-31T23:00:00.000000000  (1323648 steps, step=3600000000000 nanoseconds)

## Vertical Coordinate

In [9]:
level_candidates = [c for c in ds.coords if any(k in c.lower() for k in ["level", "pressure", "isobaric", "height"])]
for lc in level_candidates:
    lv = ds[lc].values
    print(f"{lc}: {lv}")

level: [   1    2    3    5    7   10   20   30   50   70  100  125  150  175
  200  225  250  300  350  400  450  500  550  600  650  700  750  775
  800  825  850  875  900  925  950  975 1000]

## Spatial Extent &amp; Resolution

In [10]:
spatial_keywords = {"latitude", "longitude", "lat", "lon"}
for coord_name in ds.coords:
    if coord_name.lower() in spatial_keywords or any(coord_name.lower().startswith(k) for k in spatial_keywords):
        vals = ds[coord_name].values
        step = round(float(np.diff(vals[:2])[0]), 6) if len(vals) > 1 else "N/A"
        print(f"{coord_name}: min={vals.min():.4f}  max={vals.max():.4f}  step={step}  n={len(vals)}")

latitude: min=-90.0000  max=90.0000  step=-0.25  n=721
longitude: min=0.0000  max=359.7500  step=0.25  n=1440

In [11]:
var_rows

[{'variable': '100m_u_component_of_wind',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm s**-1',
  'long_name': '100 metre U wind component',
  'uncompressed MiB': 5242402.3},
 {'variable': '100m_v_component_of_wind',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm s**-1',
  'long_name': '100 metre V wind component',
  'uncompressed MiB': 5242402.3},
 {'variable': '10m_u_component_of_neutral_wind',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm s**-1',
  'long_name': 'Neutral wind at 10 m u-component',
  'uncompressed MiB': 5242402.3},
 {'variable': '10m_u_component_of_wind',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm s**-1',
  'long_name': '10 metre U wind component',
  'uncompressed MiB': 5242402.3},
 {'variable': '10m_v_component_of_neutral_wind',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm s**-1',
  'long_name': 'Neutral wind at 10 m v-component',
  'uncompressed MiB': 5242402.3},
 {'variable': '10m_v_component_of_wind',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm s**-1',
  'long_name': '10 metre V wind component',
  'uncompressed MiB': 5242402.3},
 {'variable': '10m_wind_gust_since_previous_post_processing',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm s**-1',
  'long_name': '10 metre wind gust since previous post-processing',
  'uncompressed MiB': 5242402.3},
 {'variable': '2m_dewpoint_temperature',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'K',
  'long_name': '2 metre dewpoint temperature',
  'uncompressed MiB': 5242402.3},
 {'variable': '2m_temperature',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'K',
  'long_name': '2 metre temperature',
  'uncompressed MiB': 5242402.3},
 {'variable': 'air_density_over_the_oceans',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'kg m**-3',
  'long_name': 'Air density over the oceans',
  'uncompressed MiB': 5242402.3},
 {'variable': 'angle_of_sub_gridscale_orography',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'radians',
  'long_name': 'Angle of sub-gridscale orography',
  'uncompressed MiB': 5242402.3},
 {'variable': 'anisotropy_of_sub_gridscale_orography',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': '~',
  'long_name': 'Anisotropy of sub-gridscale orography',
  'uncompressed MiB': 5242402.3},
 {'variable': 'benjamin_feir_index',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'dimensionless',
  'long_name': 'Benjamin-Feir index',
  'uncompressed MiB': 5242402.3},
 {'variable': 'boundary_layer_dissipation',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'J m**-2',
  'long_name': 'Boundary layer dissipation',
  'uncompressed MiB': 5242402.3},
 {'variable': 'boundary_layer_height',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm',
  'long_name': 'Boundary layer height',
  'uncompressed MiB': 5242402.3},
 {'variable': 'charnock',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': '~',
  'long_name': 'Charnock',
  'uncompressed MiB': 5242402.3},
 {'variable': 'clear_sky_direct_solar_radiation_at_surface',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'J m**-2',
  'long_name': 'Clear-sky direct solar radiation at surface',
  'uncompressed MiB': 5242402.3},
 {'variable': 'cloud_base_height',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm',
  'long_name': 'Cloud base height',
  'uncompressed MiB': 5242402.3},
 {'variable': 'coefficient_of_drag_with_waves',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'dimensionless',
  'long_name': 'Coefficient of drag with waves',
  'uncompressed MiB': 5242402.3},
 {'variable': 'convective_available_potential_energy',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'J kg**-1',
  'long_name': 'Convective available potential energy',
  'uncompressed MiB': 5242402.3},
 {'variable': 'convective_inhibition',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'J kg**-1',
  'long_name': 'Convective inhibition',
  'uncompressed MiB': 5242402.3},
 {'variable': 'convective_precipitation',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm',
  'long_name': 'Convective precipitation',
  'uncompressed MiB': 5242402.3},
 {'variable': 'convective_rain_rate',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'kg m**-2 s**-1',
  'long_name': 'Convective rain rate',
  'uncompressed MiB': 5242402.3},
 {'variable': 'convective_snowfall',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm of water equivalent',
  'long_name': 'Convective snowfall',
  'uncompressed MiB': 5242402.3},
 {'variable': 'convective_snowfall_rate_water_equivalent',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'kg m**-2 s**-1',
  'long_name': 'Convective snowfall rate water equivalent',
  'uncompressed MiB': 5242402.3},
 {'variable': 'downward_uv_radiation_at_the_surface',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'J m**-2',
  'long_name': 'Downward UV radiation at the surface',
  'uncompressed MiB': 5242402.3},
 {'variable': 'duct_base_height',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm',
  'long_name': 'Duct base height',
  'uncompressed MiB': 5242402.3},
 {'variable': 'eastward_gravity_wave_surface_stress',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'N m**-2 s',
  'long_name': 'Eastward gravity wave surface stress',
  'uncompressed MiB': 5242402.3},
 {'variable': 'eastward_turbulent_surface_stress',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'N m**-2 s',
  'long_name': 'Eastward turbulent surface stress',
  'uncompressed MiB': 5242402.3},
 {'variable': 'evaporation',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm of water equivalent',
  'long_name': 'Evaporation',
  'uncompressed MiB': 5242402.3},
 {'variable': 'forecast_albedo',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': '(0 - 1)',
  'long_name': 'Forecast albedo',
  'uncompressed MiB': 5242402.3},
 {'variable': 'forecast_logarithm_of_surface_roughness_for_heat',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': '~',
  'long_name': 'Forecast logarithm of surface roughness for heat',
  'uncompressed MiB': 5242402.3},
 {'variable': 'forecast_surface_roughness',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm',
  'long_name': 'Forecast surface roughness',
  'uncompressed MiB': 5242402.3},
 {'variable': 'fraction_of_cloud_cover',
  'dims': "('time', 'level', 'latitude', 'longitude')",
  'shape': '(1323648, 37, 721, 1440)',
  'dtype': 'float32',
  'units': '(0 - 1)',
  'long_name': 'Fraction of cloud cover',
  'uncompressed MiB': 193968883.8},
 {'variable': 'free_convective_velocity_over_the_oceans',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm s**-1',
  'long_name': 'Free convective velocity over the oceans',
  'uncompressed MiB': 5242402.3},
 {'variable': 'friction_velocity',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm s**-1',
  'long_name': 'Friction velocity',
  'uncompressed MiB': 5242402.3},
 {'variable': 'geopotential',
  'dims': "('time', 'level', 'latitude', 'longitude')",
  'shape': '(1323648, 37, 721, 1440)',
  'dtype': 'float32',
  'units': 'm**2 s**-2',
  'long_name': 'Geopotential',
  'uncompressed MiB': 193968883.8},
 {'variable': 'geopotential_at_surface',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm**2 s**-2',
  'long_name': 'Geopotential',
  'uncompressed MiB': 5242402.3},
 {'variable': 'gravity_wave_dissipation',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'J m**-2',
  'long_name': 'Gravity wave dissipation',
  'uncompressed MiB': 5242402.3},
 {'variable': 'high_cloud_cover',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': '(0 - 1)',
  'long_name': 'High cloud cover',
  'uncompressed MiB': 5242402.3},
 {'variable': 'high_vegetation_cover',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': '(0 - 1)',
  'long_name': 'High vegetation cover',
  'uncompressed MiB': 5242402.3},
 {'variable': 'ice_temperature_layer_1',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'K',
  'long_name': 'Ice temperature layer 1',
  'uncompressed MiB': 5242402.3},
 {'variable': 'ice_temperature_layer_2',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'K',
  'long_name': 'Ice temperature layer 2',
  'uncompressed MiB': 5242402.3},
 {'variable': 'ice_temperature_layer_3',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'K',
  'long_name': 'Ice temperature layer 3',
  'uncompressed MiB': 5242402.3},
 {'variable': 'ice_temperature_layer_4',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'K',
  'long_name': 'Ice temperature layer 4',
  'uncompressed MiB': 5242402.3},
 {'variable': 'instantaneous_10m_wind_gust',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm s**-1',
  'long_name': 'Instantaneous 10 metre wind gust',
  'uncompressed MiB': 5242402.3},
 {'variable': 'instantaneous_eastward_turbulent_surface_stress',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'N m**-2',
  'long_name': 'Instantaneous eastward turbulent surface stress',
  'uncompressed MiB': 5242402.3},
 {'variable': 'instantaneous_large_scale_surface_precipitation_fraction',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': '(0 - 1)',
  'long_name': 'Instantaneous large-scale surface precipitation fraction',
  'uncompressed MiB': 5242402.3},
 {'variable': 'instantaneous_moisture_flux',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'kg m**-2 s**-1',
  'long_name': 'Instantaneous moisture flux',
  'uncompressed MiB': 5242402.3},
 {'variable': 'instantaneous_northward_turbulent_surface_stress',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'N m**-2',
  'long_name': 'Instantaneous northward turbulent surface stress',
  'uncompressed MiB': 5242402.3},
 {'variable': 'instantaneous_surface_sensible_heat_flux',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'W m**-2',
  'long_name': 'Instantaneous surface sensible heat flux',
  'uncompressed MiB': 5242402.3},
 {'variable': 'k_index',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'K',
  'long_name': 'K index',
  'uncompressed MiB': 5242402.3},
 {'variable': 'lake_bottom_temperature',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'K',
  'long_name': 'Lake bottom temperature',
  'uncompressed MiB': 5242402.3},
 {'variable': 'lake_cover',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': '(0 - 1)',
  'long_name': 'Lake cover',
  'uncompressed MiB': 5242402.3},
 {'variable': 'lake_depth',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm',
  'long_name': 'Lake total depth',
  'uncompressed MiB': 5242402.3},
 {'variable': 'lake_ice_depth',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm',
  'long_name': 'Lake ice total depth',
  'uncompressed MiB': 5242402.3},
 {'variable': 'lake_ice_temperature',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'K',
  'long_name': 'Lake ice surface temperature',
  'uncompressed MiB': 5242402.3},
 {'variable': 'lake_mix_layer_depth',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm',
  'long_name': 'Lake mix-layer depth',
  'uncompressed MiB': 5242402.3},
 {'variable': 'lake_mix_layer_temperature',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'K',
  'long_name': 'Lake mix-layer temperature',
  'uncompressed MiB': 5242402.3},
 {'variable': 'lake_shape_factor',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'dimensionless',
  'long_name': 'Lake shape factor',
  'uncompressed MiB': 5242402.3},
 {'variable': 'lake_total_layer_temperature',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'K',
  'long_name': 'Lake total layer temperature',
  'uncompressed MiB': 5242402.3},
 {'variable': 'land_sea_mask',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': '(0 - 1)',
  'long_name': 'Land-sea mask',
  'uncompressed MiB': 5242402.3},
 {'variable': 'large_scale_precipitation',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm',
  'long_name': 'Large-scale precipitation',
  'uncompressed MiB': 5242402.3},
 {'variable': 'large_scale_precipitation_fraction',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 's',
  'long_name': 'Large-scale precipitation fraction',
  'uncompressed MiB': 5242402.3},
 {'variable': 'large_scale_rain_rate',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'kg m**-2 s**-1',
  'long_name': 'Large scale rain rate',
  'uncompressed MiB': 5242402.3},
 {'variable': 'large_scale_snowfall',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm of water equivalent',
  'long_name': 'Large-scale snowfall',
  'uncompressed MiB': 5242402.3},
 {'variable': 'large_scale_snowfall_rate_water_equivalent',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'kg m**-2 s**-1',
  'long_name': 'Large scale snowfall rate water equivalent',
  'uncompressed MiB': 5242402.3},
 {'variable': 'leaf_area_index_high_vegetation',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm**2 m**-2',
  'long_name': 'Leaf area index, high vegetation',
  'uncompressed MiB': 5242402.3},
 {'variable': 'leaf_area_index_low_vegetation',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm**2 m**-2',
  'long_name': 'Leaf area index, low vegetation',
  'uncompressed MiB': 5242402.3},
 {'variable': 'low_cloud_cover',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': '(0 - 1)',
  'long_name': 'Low cloud cover',
  'uncompressed MiB': 5242402.3},
 {'variable': 'low_vegetation_cover',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': '(0 - 1)',
  'long_name': 'Low vegetation cover',
  'uncompressed MiB': 5242402.3},
 {'variable': 'maximum_2m_temperature_since_previous_post_processing',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'K',
  'long_name': 'Maximum temperature at 2 metres since previous post-processing',
  'uncompressed MiB': 5242402.3},
 {'variable': 'maximum_individual_wave_height',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'm',
  'long_name': 'Maximum individual wave height',
  'uncompressed MiB': 5242402.3},
 {'variable': 'maximum_total_precipitation_rate_since_previous_post_processing',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'kg m**-2 s**-1',
  'long_name': 'Maximum total precipitation rate since previous post-processing',
  'uncompressed MiB': 5242402.3},
 {'variable': 'mean_boundary_layer_dissipation',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'W m**-2',
  'long_name': 'Mean boundary layer dissipation',
  'uncompressed MiB': 5242402.3},
 {'variable': 'mean_convective_precipitation_rate',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'kg m**-2 s**-1',
  'long_name': 'Mean convective precipitation rate',
  'uncompressed MiB': 5242402.3},
 {'variable': 'mean_convective_snowfall_rate',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'kg m**-2 s**-1',
  'long_name': 'Mean convective snowfall rate',
  'uncompressed MiB': 5242402.3},
 {'variable': 'mean_direction_of_total_swell',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'degrees',
  'long_name': 'Mean direction of total swell',
  'uncompressed MiB': 5242402.3},
 {'variable': 'mean_direction_of_wind_waves',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',
  'dtype': 'float32',
  'units': 'degrees',
  'long_name': 'Mean direction of wind waves',
  'uncompressed MiB': 5242402.3},
 {'variable': 'mean_eastward_gravity_wave_surface_stress',
  'dims': "('time', 'latitude', 'longitude')",
  'shape': '(1323648, 721, 1440)',

In [12]:
ds.close()